spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BSITS
    username: BSITS
    password: BSITS
    driver-class-name: org.postgresql.Driver
mybatis:
  type-aliases-package: com.emo.demo.entity
  configuration:
   #开启驼峰映射
    map-underscore-to-camel-case: true