server:
  port: 8082
spring:
  kafka:
    consumer:
      #指定消息被消费之后自动提交偏移量（即消息的编号，表示消费到了哪个位置，消费者每消费完一条消息就会向kafka服务器汇报自己消消费到的那个消息的编号，以便于下次继续消费）。
      enable-auto-commit: true
      #消费者组
      group-id: applog
      #从最近的地方开始消费
      auto-offset-reset: latest
      bootstrap-servers: 172.20.25.84:9092